# Generated by Django 3.1.3 on 2021-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='receive_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='receive_notification',
            field=models.BooleanField(default=False),
        ),
    ]
