# Generated by Django 3.1.3 on 2021-11-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211107_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
