# Generated by Django 3.1.3 on 2021-11-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211107_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='registered',
        ),
    ]
